[tool.poetry]
name = "frc-docs"
version = "9999"
description = ""
authors = []

[tool.poetry.dependencies]
black = ">=25.1.0,<26.0.0"
python = ">=3.11,<3.14"
doc8 = "==2.0.0"
docutils = "==0.21.2"
fonttools = {version = "==4.58.4", extras = ["woff"]}
jsmin = "==3.0.1"
latex = "==0.7.0"
markdown2 = "==2.5.3"
sphinx = "==8.2.3"
sphinx_design = "==0.6.1"
sphinx_copybutton = "==0.5.2"
sphinx-hoverxref = "==1.4.0"
sphinx-last-updated-by-git = "==0.3.8"
sphinx-notfound-page = "==1.1.0"
sphinx-tabs = "==3.4.5"
sphinx-toolbox = "==4.0.0"
modern-sphinx-version-warning = "==1.1.6"
sphinxcontrib-htmlhelp = "==2.1.0"
sphinxcontrib-serializinghtml = "==2.0.0"
sphinxcontrib-svg2pdfconverter = "==1.3.0"
sphinxcontrib-video = "==0.4.1"
sphinx_contributors = "==0.2.7"
sphinxext-delta = "==0.3.1"
sphinxext-mimic = "==0.1.1"
sphinxext-opengraph = "==0.10.0"
sphinxext-photofinish = "==0.1.11"
sphinxext-rediraffe = "==0.2.7"
sphinxext-remoteliteralinclude = "==0.6.0"
sphinxext-toptranslators = "==0.1.3"
frccontrol = "==2024.23"
furo = "==2024.08.06"
sphinx-build-compatibility = {git = "https://github.com/readthedocs/sphinx-build-compatibility"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
